[package]
edition = "2021"
name = "transmuter_upgrade"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
slug = "0.1.4"
prettytable-rs = "0.10.0"
csv = "1.3.0"
